[package]
name = "kaige-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# kaige = {path = ".."}
winit = "0.26.0"
wgpu = "0.12.0"
env_logger = "0.9"
log = "0.4"
pollster = "0.2"

